name: TalismanManager
version: '1.0'
main: org.frags.talismanManager.TalismanMain
api-version: '1.21'
commands:
  talisman:
    description: "Talisman open menu"
    aliases:
      - talismanes
      - talismans
      - talis
      - ab
      - accessorybag
permissions:
  talisman.slots.6:
    description: Otorga 6 filas en el talismán.
    default: false
  talisman.slots.5:
    description: Otorga 5 filas en el talismán.
    default: false
  talisman.slots.4:
    description: Otorga 4 filas en el talismán.
    default: false
  talisman.slots.3:
    description: Otorga 3 filas en el talismán.
    default: false
  talisman.slots.2:
    description: Otorga 2 filas en el talismán.
    default: false